using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public partial class GameManager: MonoBehaviour
{
    public static string s_speed = "Speed",
        s_rot = "Rot",
        s_state_change = "State_Change",
        s_state_type = "State_Type",
        s_footstep = "Footstep",
        s_charge_normal = "Charge_Normal",
        s_player = "Player",
        s_monster = "Monster",
        s_ladder = "Ladder",
        s_ladder_speed = "Ladder_Speed",
        s_transition = "Transition",
        s_forcetransition = "ForceTransition",
        s_force = "Force",
        s_hit = "Hit",
        s_hit_additive = "Hit_Additive",
        s_hit_rot = "Hit_Rot",
        s_hit_type = "Hit_Type",
        s_turn = "Turn",
        s_publiccolor = "_PublicColor",
        s_leftstate = "LeftState",
        s_chargeenterindex = "ChargeEnterIndex",
        s_shadow = "Shadow",
        s_fadeamount = "_FadeAmount",
        s_chromaberramount = "_ChromAberrAmount",
        s_radius = "_radius",
        s_size = "_size",
        s_wavesize = "_wavesize",
        s_position = "_position",
        s_125ms = "125ms",
        s_advanceddissolvecutoutstandardmap1 = "_AdvancedDissolveCutoutStandardMap1",
        s_basemap = "_BaseMap",
        s_maincolor = "_MainColor",
        s_bluramount = "_BlurAmount",
        s_colour = "_Colour",
        s_roll = "Roll",
        s_unscaledtime = "_UnscaledTime",
        s_pattern = "Pattern",
        s_rolltransition = "RollTransition",
        s_burn = "Burn",
        s_feather = "Feather",
        s_attackready = "AttackReady",
        s_cancounter = "CanCounter",
        s_concrete = "Concrete",
        s_stone = "Stone",
        s_sparkable = "Sparkable",
        s_prop = "Prop",
        s_grass = "Grass",
        s_call = "Call",
        s_flight = "Flight",
        s_flight_x = "Flight_X",
        s_flight_y = "Flight_Y",
        s_turn_l = "Turn_L",
        s_turn_r = "Turn_R",
        s_greyscaleblend = "_GreyscaleBlend",
        s_alphaoutlinecolor = "_AlphaOutlineColor",
        s_screen_colour = "_Screen_Colour",
        s_saturation = "_saturation",
        s_finish = "Finish",
        s_alphaoutlineblend = "_AlphaOutlineBlend",
        s_death = "Death",
        s_movex = "MoveX",
        s_movey = "MoveY",
        s_dissolveamount = "_DissolveAmount",
        s_dissolvemap = "_DissolveMap";
    //적 애니메이션 
    public static string
        s_deathflip = "Death_Flip",
        s_deathnorm = "Death_Norm",
        s_hitstrong1 = "Hit_Strong_1",
        s_hitstrong2 = "Hit_Strong_2",
        s_idle = "Idle",
        s_smashbegin = "Smash_Begin",
        s_smashloop = "Smash_Loop",
        s_smashfin = "Smash_Fin",
        s_spawn = "Spawn",
        s_stunbegin = "Stun_Begin",
        s_stunloop = "Stun_Loop",
        s_stunfin = "Stun_Fin",
        s_run = "Run",
        s_strafeleft = "Strafe_Left",
        s_straferight = "Strafe_Right",
        s_strafefwd = "Strafe_Fwd";
}
